export enum R {
  PLAYER_HP          = 'player_hp',
  PLAYER_MAX_HP      = 'player_max_hp',
  HOUSE_HP           = 'house_hp',
  HOUSE_MAX_HP       = 'house_max_hp',
  INVENTORY          = 'inventory',
  HOTBAR             = 'hotbar',
  ACTIVE_SLOT        = 'active_slot',
  DAY_NUMBER         = 'day_number',
  PHASE              = 'phase',
  PHASE_TIMER        = 'phase_timer',
  WAVE_ACTIVE        = 'wave_active',
  ENEMIES_REMAINING  = 'enemies_remaining',
  NIGHT_NUMBER       = 'night_number',
  CRAFTING_OPEN      = 'crafting_open',
  MINER_OPEN         = 'miner_open',
  MINER_POWER        = 'miner_power',
  MINER_HAS_PICKAXE  = 'miner_has_pickaxe',
}
